package com.example.planner.widgets

import com.example.planner.R
import com.example.planner.MainActivity

import android.content.Context
import android.content.Intent
import android.widget.RemoteViews
import android.widget.RemoteViewsService
import org.json.JSONArray
import org.json.JSONObject

class TimetableWidgetService : RemoteViewsService() {
    override fun onGetViewFactory(intent: Intent): RemoteViewsFactory {
        val appWidgetId = intent.getIntExtra(
            android.appwidget.AppWidgetManager.EXTRA_APPWIDGET_ID,
            android.appwidget.AppWidgetManager.INVALID_APPWIDGET_ID
        )
        return TimetableViewsFactory(this.applicationContext, appWidgetId)
    }
}

class TimetableViewsFactory(private val context: Context, private val appWidgetId: Int) : RemoteViewsService.RemoteViewsFactory {

    private var items = ArrayList<JSONObject>()

    override fun onCreate() {
        loadData()
    }

    override fun onDataSetChanged() {
        loadData()
    }

    private fun loadData() {
        items.clear()
        val prefNames = listOf(
            "HomeWidgetPreferences",
            "FlutterSharedPreferences",
            "${context.packageName}_preferences"
        )

        var daysJsonStr: String? = null
        var timetableJsonStr: String? = null
        var selectedDayIndex = -1

        for (name in prefNames) {
            val prefs = context.getSharedPreferences(name, Context.MODE_PRIVATE)
            if (daysJsonStr.isNullOrEmpty()) {
                daysJsonStr = prefs.getString("widget_timetable_days_json", null) ?: prefs.getString("flutter.widget_timetable_days_json", null)
            }
            if (timetableJsonStr.isNullOrEmpty()) {
                timetableJsonStr = prefs.getString("timetable_json", null) ?: prefs.getString("flutter.timetable_json", null)
            }
            if (selectedDayIndex == -1) {
                if (prefs.contains("widget_selected_day") || prefs.contains("flutter.widget_selected_day")) {
                    val value = prefs.all["widget_selected_day"] ?: prefs.all["flutter.widget_selected_day"]
                    selectedDayIndex = (value as? Number)?.toInt() ?: -1
                }
            }
        }

        if (selectedDayIndex < 0 || selectedDayIndex > 6) {
            val nowWeekday = java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_WEEK)
            selectedDayIndex = if (nowWeekday == java.util.Calendar.SATURDAY || nowWeekday == java.util.Calendar.SUNDAY) 0 else (nowWeekday - 2 + 7) % 7
            if (selectedDayIndex > 6) selectedDayIndex = 0
        }

        // 1. Try reading pre-computed day cards generated by Flutter
        try {
            if (!daysJsonStr.isNullOrEmpty()) {
                val daysObj = JSONObject(daysJsonStr)
                val dayArray = daysObj.optJSONArray(selectedDayIndex.toString())
                if (dayArray != null) {
                    for (i in 0 until dayArray.length()) {
                        items.add(dayArray.getJSONObject(i))
                    }
                }
            }
        } catch (e: Exception) {
            android.util.Log.e("TimetableWidget", "Error reading days JSON: $e")
        }

        // 2. Fallback to today's timetable list if day cards are not populated
        if (items.isEmpty() && !timetableJsonStr.isNullOrEmpty()) {
            try {
                val array = JSONArray(timetableJsonStr)
                for (i in 0 until array.length()) {
                    items.add(array.getJSONObject(i))
                }
            } catch (e: Exception) {
                android.util.Log.e("TimetableWidget", "Error fallback timetable JSON: $e")
            }
        }
    }

    override fun onDestroy() {
        items.clear()
    }

    override fun getCount(): Int {
        return items.size
    }

    override fun getViewAt(position: Int): RemoteViews? {
        if (position < 0 || position >= items.size) return null

        val item = items[position]

        val appWidgetManager = android.appwidget.AppWidgetManager.getInstance(context)
        val options = appWidgetManager.getAppWidgetOptions(appWidgetId)

        // Read orientation-safe widget height
        val isPortrait = context.resources.configuration.orientation != android.content.res.Configuration.ORIENTATION_LANDSCAPE
        var widgetH = 0

        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
            val sizes = options.getParcelableArrayList<android.util.SizeF>(android.appwidget.AppWidgetManager.OPTION_APPWIDGET_SIZES)
            if (!sizes.isNullOrEmpty()) {
                val matchingSize = if (isPortrait) {
                    sizes.minByOrNull { it.width } ?: sizes[0]
                } else {
                    sizes.maxByOrNull { it.width } ?: sizes[0]
                }
                widgetH = matchingSize.height.toInt()
            }
        }

        if (widgetH <= 0) {
            widgetH = if (isPortrait) {
                val h = options.getInt(android.appwidget.AppWidgetManager.OPTION_APPWIDGET_MAX_HEIGHT, 0)
                if (h > 0) h else options.getInt(android.appwidget.AppWidgetManager.OPTION_APPWIDGET_MIN_HEIGHT, 140)
            } else {
                val h = options.getInt(android.appwidget.AppWidgetManager.OPTION_APPWIDGET_MIN_HEIGHT, 0)
                if (h > 0) h else options.getInt(android.appwidget.AppWidgetManager.OPTION_APPWIDGET_MAX_HEIGHT, 140)
            }
        }

        // Header & container padding overhead:
        // Container padding (10dp top + 10dp bottom = 20dp)
        // Header row height (approx 28dp)
        // ListView marginTop (4dp)
        // Total fixed overhead = 52dp
        val overheadDp = 52
        val availableH = (widgetH - overheadDp).coerceAtLeast(50)

        // Determine target visible card count dynamically based on available height:
        // ~50-130dp (2 rows): 1 card
        // ~130-230dp (3-4 rows): 2 cards
        // ~230-330dp (5 rows): 3 cards
        // ~330-430dp (6-7 rows): 4 cards
        // >= 430dp (8+ rows): 5+ cards
        val targetCount = when {
            availableH < 130 -> 1
            availableH < 230 -> 2
            availableH < 330 -> 3
            availableH < 430 -> 4
            else -> (availableH / 95).coerceAtLeast(4)
        }

        val dividerDp = 4
        val totalDividers = (targetCount - 1) * dividerDp
        // Compute the EXACT item height so N items + dividers completely and cleanly fill the available height
        val itemHeightDp = ((availableH - totalDividers).toFloat() / targetCount.toFloat()).coerceAtLeast(50f)

        val itemLayoutId = R.layout.widget_item
        val itemViews = RemoteViews(context.packageName, itemLayoutId)

        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
            itemViews.setViewLayoutHeight(
                R.id.widget_item_container,
                itemHeightDp,
                android.util.TypedValue.COMPLEX_UNIT_DIP
            )
        }

        val courseCode = item.optString("courseCode", "")
        val courseTitle = item.optString("courseTitle", "").ifEmpty {
            item.optString("courseName", "Free")
        }
        val timeRoom = item.optString("timeStr", "--")
        val sessionType = item.optString("sessionType", "Lecture")
        val teacher = item.optString("teacherName", "")
        val pct = item.optInt("attendancePct", -1)
        val ratio = item.optString("attendanceRatio", "")

        val typeAndCode = if (courseCode.isNotEmpty() && sessionType.isNotEmpty()) {
            "$sessionType · $courseCode"
        } else if (courseCode.isNotEmpty()) {
            courseCode
        } else {
            sessionType
        }

        itemViews.setTextViewText(R.id.item_session_type, typeAndCode)
        itemViews.setTextViewText(R.id.item_course, courseTitle)

        // Combine time + teacher on the same line so subject name doesn't push teacher off-screen.
        // The full item layout keeps R.id.item_teacher hidden and uses the combined string.
        val timeAndTeacher = if (teacher.isNotEmpty()) "$timeRoom · $teacher" else timeRoom
        itemViews.setTextViewText(R.id.item_time_period, timeAndTeacher)
        itemViews.setViewVisibility(R.id.item_teacher, android.view.View.GONE)

        if (sessionType == "INFO") {
            itemViews.setViewVisibility(R.id.item_session_type, android.view.View.GONE)
            itemViews.setViewVisibility(R.id.item_time_period, android.view.View.GONE)
            itemViews.setViewVisibility(R.id.item_teacher, android.view.View.GONE)
            itemViews.setViewVisibility(R.id.item_attendance_container, android.view.View.GONE)
        } else {
            itemViews.setViewVisibility(R.id.item_session_type, android.view.View.VISIBLE)
            itemViews.setViewVisibility(R.id.item_time_period, android.view.View.VISIBLE)

            if (ratio.isNotEmpty() && pct >= 0) {
                itemViews.setViewVisibility(R.id.item_attendance_container, android.view.View.VISIBLE)
                itemViews.setTextViewText(R.id.item_attendance_pct, "${pct}%")
                itemViews.setTextViewText(R.id.item_attendance_ratio, ratio)
            } else {
                itemViews.setViewVisibility(R.id.item_attendance_container, android.view.View.GONE)
            }
        }

        val fillInIntent = Intent()
        itemViews.setOnClickFillInIntent(R.id.widget_item_container, fillInIntent)

        // Tint attendance percentage with user accent color if set
        val accentColor = readAccentColor()
        if (accentColor != null && ratio.isNotEmpty() && pct >= 0) {
            itemViews.setTextColor(R.id.item_attendance_pct, accentColor)
        }

        return itemViews
    }

    override fun getLoadingView(): RemoteViews? = null

    override fun getViewTypeCount(): Int = 2

    override fun getItemId(position: Int): Long = position.toLong()

    override fun hasStableIds(): Boolean = true

    /** Read the accent color stored by Flutter's ThemeService / HomeWidgetService.
     *  Flutter SharedPreferences stores ints as Long on Android — must NOT use getInt(). */
    private fun readAccentColor(): Int? {
        val prefNames = listOf(
            "HomeWidgetPreferences",
            "FlutterSharedPreferences",
            "${context.packageName}_preferences"
        )
        for (name in prefNames) {
            val p = context.getSharedPreferences(name, android.content.Context.MODE_PRIVATE)
            for (key in listOf("app_theme_widget_accent", "flutter.app_theme_widget_accent")) {
                val raw = p.all[key] ?: continue
                val color = when (raw) {
                    is Int -> raw
                    is Long -> raw.toInt()
                    else -> continue
                }
                if (color != 0) return color
            }
        }
        return null
    }
}
